/*
 * File: pa3Globals.c
 * Description: Global variables for pa3.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

/*
 * C standard library headers 
 */
#include <stddef.h> // offsetof

/*
 * Assignment header(s)
 */
#include "pa3.h"

// Used in hash()
int HashPrime = HASH_PRIME;
int HashStartVal = HASH_START_VAL;
